<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <!-- 顶层聚合工程，仅做模块管理，不直接打包代码 -->
  <groupId>com.dsq</groupId>
  <artifactId>pkm-cli</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>pkm-cli</name>
  <url>http://maven.apache.org</url>

  <modules>
    <!-- CLI 核心模块（使用根目录 src 下的代码） -->
    <module>cli</module>
    <!-- Spring Boot Web 后端 -->
    <module>pkm-web</module>
    <!-- Spring Boot test 项目 -->
    <module>test</module>
  </modules>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
  </properties>

</project>
